version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/marketing
hooks:
  ApplicationStop:
    - location: server/stop_server
      timeout: 300
      runas: root
  BeforeInstall:
    - location: server/install_dependencies
      timeout: 300
      runas: root
  ApplicationStart:
    - location: server/start_server
      timeout: 300
      runas: root
  


